name: openshock_mobile
description: "The Official OpenShock Mobile Application"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # Base Flutter Dependencies
  cupertino_icons: ^1.0.8

  # HTTP and Networking Dependencies
  dio: ^5.9.0
  dio_cookie_manager: ^3.3.0
  cookie_jar: ^4.0.8

  # Preference and Storage Dependencies
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^10.0.0

  # State Management
  provider: ^6.1.5

  # UI Utilities
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Base Flutter Dev Dependencies
  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/os/
